import uuid
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.dependencies import require_roles, get_scoped_project
from app.models.srs_version import SRSVersion
from app.models.user import User
from app.schemas.srs import SRSVersionRead
from app.services.storage_service import StorageService

router = APIRouter(prefix="/srs", tags=["srs"])

from app.models.requirement_atom import RequirementAtom

@router.get("/project/{project_id}/latest")
async def get_latest_srs(
    project_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    """
    Get the latest SRS version with extracted requirement atoms and dynamic sections.
    """
    await get_scoped_project(project_id, current_user, db)

    q = (
        select(SRSVersion)
        .where(SRSVersion.project_id == project_id)
        .order_by(SRSVersion.created_at.desc())
        .limit(1)
    )
    result = await db.execute(q)
    srs = result.scalar_one_or_none()

    if not srs:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No SRS document found for this project."
        )

    # Fetch active requirement atoms for this project/session
    atoms_res = await db.execute(
        select(RequirementAtom)
        .where(
            (RequirementAtom.session_id == srs.session_id) | (RequirementAtom.project_id == project_id)
        )
        .where(RequirementAtom.status == "active")
    )
    atoms = atoms_res.scalars().all()

    sections = [
        {
            "title": "1. Executive Summary & Overview",
            "content": f"Software Requirements Specification (v{srs.version}) generated by {srs.generated_by}. This specification maps all verified functional requirements, constraints, and system specifications captured during client gathering sessions."
        },
        {
            "title": "2. Functional Requirements",
            "content": "\n\n".join([
                f"[{idx}] {atom.subject}: {atom.action}" + (f" (Constraint: {atom.constraint_text})" if atom.constraint_text else "")
                for idx, atom in enumerate(atoms, start=1)
            ]) if atoms else "No active functional requirements extracted yet."
        },
        {
            "title": "3. Requirement Statements (Raw Captures)",
            "content": "\n".join([
                f"- \"{atom.raw_text}\"" for atom in atoms
            ]) if atoms else "No raw requirement statements captured."
        }
    ]

    download_url = StorageService.get_download_url(srs.file_url)

    return {
        "id": srs.id,
        "version": srs.version,
        "download_url": download_url,
        "sections": sections,
        "atoms": [
            {
                "id": str(a.id),
                "subject": a.subject,
                "action": a.action,
                "constraint_text": a.constraint_text,
                "raw_text": a.raw_text
            }
            for a in atoms
        ],
        "created_at": srs.created_at,
        "generated_by": srs.generated_by,
        "change_summary": srs.change_summary
    }


import os
from pathlib import Path
from fastapi.responses import FileResponse, RedirectResponse
from app.services.storage_service import get_s3_client, _BASE_DIR

@router.get("/download-file")
async def download_srs_file(key: str):
    """
    Serves the SRS Word .docx file for local/mock storage mode or redirects to S3.
    """
    s3 = get_s3_client()
    if s3 is None:
        file_path = _BASE_DIR / "storage_files" / key
        if not file_path.exists():
            import docx
            file_path.parent.mkdir(parents=True, exist_ok=True)
            doc = docx.Document()
            doc.add_heading("Software Requirements Specification (SRS)", 0)
            doc.add_paragraph("Requirements gathering specification document.")
            doc.save(str(file_path))

        filename = os.path.basename(key)
        return FileResponse(
            path=str(file_path),
            filename=filename,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
        )
    else:
        url = StorageService.get_download_url(key)
        return RedirectResponse(url=url)


@router.get("/project/{project_id}/versions", response_model=List[SRSVersionRead])
async def list_srs_versions(
    project_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    limit: int = 50,
    offset: int = 0,
    db: AsyncSession = Depends(get_db)
):
    """
    List all SRS versions for a project with valid download URLs.
    """
    await get_scoped_project(project_id, current_user, db)

    q = (
        select(SRSVersion)
        .where(SRSVersion.project_id == project_id)
        .order_by(SRSVersion.created_at.desc())
        .limit(limit)
        .offset(offset)
    )
    result = await db.execute(q)
    versions = result.scalars().all()

    formatted_versions = []
    for v in versions:
        v_dict = {
            "id": v.id,
            "project_id": v.project_id,
            "session_id": v.session_id,
            "version": v.version,
            "file_url": StorageService.get_download_url(v.file_url),
            "generated_by": v.generated_by,
            "change_summary": v.change_summary,
            "llm_model": v.llm_model,
            "prompt_version": v.prompt_version,
            "generation_latency_ms": v.generation_latency_ms,
            "created_at": v.created_at,
        }
        formatted_versions.append(v_dict)
    return formatted_versions
@router.get("/version/{version_id}")
async def get_srs_version_details(
    version_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    """
    Get full details (sections, atoms, download URL) for a specific SRS revision version.
    """
    srs = await db.get(SRSVersion, version_id)
    if not srs:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="SRS version not found."
        )

    await get_scoped_project(srs.project_id, current_user, db)

    atoms_res = await db.execute(
        select(RequirementAtom)
        .where(
            (RequirementAtom.session_id == srs.session_id) | (RequirementAtom.project_id == srs.project_id)
        )
        .where(RequirementAtom.status == "active")
    )
    atoms = atoms_res.scalars().all()

    sections = [
        {
            "title": "1. Executive Summary & Overview",
            "content": f"Software Requirements Specification (v{srs.version}) generated by {srs.generated_by}. This specification maps all verified functional requirements, constraints, and system specifications captured during client gathering sessions."
        },
        {
            "title": "2. Functional Requirements",
            "content": "\n\n".join([
                f"[{idx}] {atom.subject}: {atom.action}" + (f" (Constraint: {atom.constraint_text})" if atom.constraint_text else "")
                for idx, atom in enumerate(atoms, start=1)
            ]) if atoms else "No active functional requirements extracted yet."
        },
        {
            "title": "3. Requirement Statements (Raw Captures)",
            "content": "\n".join([
                f"- \"{atom.raw_text}\"" for atom in atoms
            ]) if atoms else "No raw requirement statements captured."
        }
    ]

    download_url = StorageService.get_download_url(srs.file_url)

    return {
        "id": srs.id,
        "version": srs.version,
        "download_url": download_url,
        "sections": sections,
        "atoms": [
            {
                "id": str(a.id),
                "subject": a.subject,
                "action": a.action,
                "constraint_text": a.constraint_text,
                "raw_text": a.raw_text
            }
            for a in atoms
        ],
        "created_at": srs.created_at,
        "generated_by": srs.generated_by,
        "change_summary": srs.change_summary
    }


from app.services.srs_generator import SRSGenerator

@router.post("/project/{project_id}/generate")
async def generate_project_srs(
    project_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    """
    Generate an SRS document for the project's most recent session.
    """
    await get_scoped_project(project_id, current_user, db)

    from app.models.session import Session
    sess_res = await db.execute(
        select(Session)
        .where(Session.project_id == project_id)
        .order_by(Session.started_at.desc())
        .limit(1)
    )
    latest_session = sess_res.scalar_one_or_none()
    if not latest_session:
        latest_session = Session(
            project_id=project_id,
            client_id=current_user.id if current_user.role == "client" else None,
            status="completed"
        )
        db.add(latest_session)
        await db.commit()
        await db.refresh(latest_session)

    srs = await SRSGenerator.generate_srs(latest_session.id, db)
    download_url = StorageService.get_download_url(srs.file_url)

    return {
        "id": srs.id,
        "version": srs.version,
        "download_url": download_url,
        "created_at": srs.created_at
    }
