import uuid
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.dependencies import require_roles, get_scoped_project
from app.models.srs_version import SRSVersion
from app.models.user import User
from app.schemas.srs import SRSVersionRead
from app.services.storage_service import StorageService

router = APIRouter(prefix="/srs", tags=["srs"])

from app.models.requirement_atom import RequirementAtom

@router.get("/project/{project_id}/latest")
async def get_latest_srs(
    project_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    await get_scoped_project(project_id, current_user, db)

    q = (
        select(SRSVersion)
        .where(SRSVersion.project_id == project_id)
        .order_by(SRSVersion.created_at.desc())
        .limit(1)
    )
    result = await db.execute(q)
    srs = result.scalar_one_or_none()

    if not srs:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No SRS document found for this project."
        )

    from app.models.contradiction import Contradiction
    from app.models.session import Session
    from app.models.change_request import ChangeRequest
    from sqlalchemy import or_

    session_ids_q = select(Session.id).where(Session.project_id == project_id)
    cr_ids_q = select(ChangeRequest.id).where(ChangeRequest.project_id == project_id)
    pending_c_res = await db.execute(
        select(Contradiction).where(
            or_(
                Contradiction.session_id.in_(session_ids_q),
                Contradiction.change_request_id.in_(cr_ids_q)
            ),
            Contradiction.status == "pending"
        )
    )
    pending_c_list = pending_c_res.scalars().all()
    pending_atom_ids = set()
    for pc in pending_c_list:
        if pc.atom_1_id:
            pending_atom_ids.add(pc.atom_1_id)
        if pc.atom_2_id:
            pending_atom_ids.add(pc.atom_2_id)

    atoms_res = await db.execute(
        select(RequirementAtom)
        .where(
            (RequirementAtom.session_id == srs.session_id) | (RequirementAtom.project_id == project_id)
        )
        .where(RequirementAtom.status == "active")
    )
    all_active_atoms = atoms_res.scalars().all()
    atoms = [a for a in all_active_atoms if a.id not in pending_atom_ids]

    sections = [
        {
            "title": "1. Executive Summary & Overview",
            "content": f"Software Requirements Specification (v{srs.version}) generated by {srs.generated_by}. This specification maps all verified functional requirements, constraints, and system specifications captured during client gathering sessions."
        },
        {
            "title": "2. Functional Requirements",
            "content": "\n\n".join([
                f"[{idx}] {atom.subject or 'Unspecified'}: {atom.action or 'Unspecified'}" + (f" (Constraint: {atom.constraint_text})" if atom.constraint_text else "")
                for idx, atom in enumerate(atoms, start=1)
            ]) if atoms else "No active functional requirements extracted yet."
        },
        {
            "title": "3. Requirement Statements (Raw Captures)",
            "content": "\n".join([
                f"- \"{atom.raw_text}\"" for atom in atoms
            ]) if atoms else "No raw requirement statements captured."
        }
    ]

    download_url = StorageService.get_download_url(srs.file_url)

    return {
        "id": srs.id,
        "version": srs.version,
        "download_url": download_url,
        "sections": sections,
        "atoms": [
            {
                "id": str(a.id),
                "subject": a.subject,
                "action": a.action,
                "constraint_text": a.constraint_text,
                "raw_text": a.raw_text
            }
            for a in atoms
        ],
        "created_at": srs.created_at,
        "generated_by": srs.generated_by,
        "change_summary": srs.change_summary
    }

import os
from pathlib import Path
from fastapi.responses import FileResponse, RedirectResponse
from app.services.storage_service import get_s3_client, _BASE_DIR

@router.get("/download-file")
async def download_srs_file(
    key: str,
    token: Optional[str] = Query(None),
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db),
):
    if ".." in key:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid file key.",
        )
    s3 = get_s3_client()
    if s3 is None:
        file_path = _BASE_DIR / "storage_files" / key
        if not file_path.exists():
            import docx
            from docx.shared import Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            file_path.parent.mkdir(parents=True, exist_ok=True)
            doc = docx.Document()
            title_p = doc.add_paragraph()
            title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            r = title_p.add_run("SOFTWARE REQUIREMENTS SPECIFICATION (SRS)")
            r.font.name = "Arial"
            r.font.size = Pt(20)
            r.font.bold = True
            r.font.color.rgb = RGBColor(30, 58, 138)
            doc.add_paragraph("ReqSense AI Requirements Specification Document.")
            doc.save(str(file_path))

        filename = os.path.basename(key)
        if not filename.endswith(".docx"):
            filename = f"{filename}.docx"

        return FileResponse(
            path=str(file_path),
            filename=filename,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'}
        )
    else:
        url = StorageService.get_download_url(key)
        return RedirectResponse(url=url)

@router.get("/project/{project_id}/versions", response_model=List[SRSVersionRead])
async def list_srs_versions(
    project_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    limit: int = 50,
    offset: int = 0,
    db: AsyncSession = Depends(get_db)
):
    await get_scoped_project(project_id, current_user, db)

    q = (
        select(SRSVersion)
        .where(SRSVersion.project_id == project_id)
        .order_by(SRSVersion.created_at.desc())
        .limit(limit)
        .offset(offset)
    )
    result = await db.execute(q)
    versions = result.scalars().all()

    formatted_versions = []
    for v in versions:
        v_dict = {
            "id": v.id,
            "project_id": v.project_id,
            "session_id": v.session_id,
            "version": v.version,
            "file_url": StorageService.get_download_url(v.file_url),
            "generated_by": v.generated_by,
            "change_summary": v.change_summary,
            "llm_model": v.llm_model,
            "prompt_version": v.prompt_version,
            "generation_latency_ms": v.generation_latency_ms,
            "created_at": v.created_at,
        }
        formatted_versions.append(v_dict)
    return formatted_versions
@router.get("/version/{version_id}")
async def get_srs_version_details(
    version_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    srs = await db.get(SRSVersion, version_id)
    if not srs:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="SRS version not found."
        )

    from app.models.contradiction import Contradiction
    from app.models.session import Session
    from app.models.change_request import ChangeRequest
    from sqlalchemy import or_

    session_ids_q = select(Session.id).where(Session.project_id == srs.project_id)
    cr_ids_q = select(ChangeRequest.id).where(ChangeRequest.project_id == srs.project_id)
    pending_c_res = await db.execute(
        select(Contradiction).where(
            or_(
                Contradiction.session_id.in_(session_ids_q),
                Contradiction.change_request_id.in_(cr_ids_q)
            ),
            Contradiction.status == "pending"
        )
    )
    pending_c_list = pending_c_res.scalars().all()
    pending_atom_ids = set()
    for pc in pending_c_list:
        if pc.atom_1_id:
            pending_atom_ids.add(pc.atom_1_id)
        if pc.atom_2_id:
            pending_atom_ids.add(pc.atom_2_id)

    atoms_res = await db.execute(
        select(RequirementAtom)
        .where(
            (RequirementAtom.session_id == srs.session_id) | (RequirementAtom.project_id == srs.project_id)
        )
        .where(RequirementAtom.status == "active")
    )
    all_active_atoms = atoms_res.scalars().all()
    atoms = [a for a in all_active_atoms if a.id not in pending_atom_ids]

    sections = [
        {
            "title": "1. Executive Summary & Overview",
            "content": f"Software Requirements Specification (v{srs.version}) generated by {srs.generated_by}. This specification maps all verified functional requirements, constraints, and system specifications captured during client gathering sessions."
        },
        {
            "title": "2. Functional Requirements",
            "content": "\n\n".join([
                f"[{idx}] {atom.subject or 'Unspecified'}: {atom.action or 'Unspecified'}" + (f" (Constraint: {atom.constraint_text})" if atom.constraint_text else "")
                for idx, atom in enumerate(atoms, start=1)
            ]) if atoms else "No active functional requirements extracted yet."
        },
        {
            "title": "3. Requirement Statements (Raw Captures)",
            "content": "\n".join([
                f"- \"{atom.raw_text}\"" for atom in atoms
            ]) if atoms else "No raw requirement statements captured."
        }
    ]

    download_url = StorageService.get_download_url(srs.file_url)

    return {
        "id": srs.id,
        "version": srs.version,
        "download_url": download_url,
        "sections": sections,
        "atoms": [
            {
                "id": str(a.id),
                "subject": a.subject,
                "action": a.action,
                "constraint_text": a.constraint_text,
                "raw_text": a.raw_text
            }
            for a in atoms
        ],
        "created_at": srs.created_at,
        "generated_by": srs.generated_by,
        "change_summary": srs.change_summary
    }

from app.services.srs_generator import SRSGenerator

@router.post("/project/{project_id}/generate")
async def generate_project_srs(
    project_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    await get_scoped_project(project_id, current_user, db)

    from app.models.session import Session
    sess_res = await db.execute(
        select(Session)
        .where(Session.project_id == project_id)
        .order_by(Session.started_at.desc())
        .limit(1)
    )
    latest_session = sess_res.scalar_one_or_none()

    if not latest_session:
        latest_session = Session(
            id=uuid.uuid4(),
            project_id=project_id,
            client_id=current_user.id if current_user.role == "client" else None,
            status="completed",
        )
        db.add(latest_session)
        await db.commit()
        await db.refresh(latest_session)

    srs = await SRSGenerator.generate_srs(latest_session.id, db)
    download_url = StorageService.get_download_url(srs.file_url)

    return {
        "id": srs.id,
        "version": srs.version,
        "download_url": download_url,
        "created_at": srs.created_at
    }

@router.get("/project/{project_id}/diff")
async def diff_srs_versions(
    project_id: uuid.UUID,
    v1_id: uuid.UUID,
    v2_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    await get_scoped_project(project_id, current_user, db)

    srs_v1 = await db.get(SRSVersion, v1_id)
    srs_v2 = await db.get(SRSVersion, v2_id)

    if not srs_v1 or not srs_v2 or srs_v1.project_id != project_id or srs_v2.project_id != project_id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Specified SRS versions not found for this project."
        )

    atoms_v1_res = await db.execute(
        select(RequirementAtom)
        .where(
            RequirementAtom.project_id == project_id,
            RequirementAtom.created_at <= srs_v1.created_at
        )
    )
    atoms_v1 = {a.id: a for a in atoms_v1_res.scalars().all()}

    atoms_v2_res = await db.execute(
        select(RequirementAtom)
        .where(
            RequirementAtom.project_id == project_id,
            RequirementAtom.created_at <= srs_v2.created_at
        )
    )
    atoms_v2 = {a.id: a for a in atoms_v2_res.scalars().all()}

    added = [
        {"id": str(a.id), "raw_text": a.raw_text, "subject": a.subject, "action": a.action}
        for aid, a in atoms_v2.items() if aid not in atoms_v1
    ]
    removed = [
        {"id": str(a.id), "raw_text": a.raw_text, "subject": a.subject, "action": a.action}
        for aid, a in atoms_v1.items() if aid not in atoms_v2
    ]

    return {
        "v1": {"id": str(srs_v1.id), "version": srs_v1.version, "created_at": srs_v1.created_at},
        "v2": {"id": str(srs_v2.id), "version": srs_v2.version, "created_at": srs_v2.created_at},
        "added_requirements": added,
        "removed_requirements": removed,
        "net_change_count": len(added) - len(removed)
    }
