import uuid
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.dependencies import require_roles, get_scoped_project
from app.models.srs_version import SRSVersion
from app.models.user import User
from app.schemas.srs import SRSVersionRead
from app.services.storage_service import StorageService

import logging

router = APIRouter(prefix="/srs", tags=["srs"])

from app.models.requirement_atom import RequirementAtom

logger = logging.getLogger(__name__)

def _clean_subject_domain(raw_subject: Optional[str]) -> str:
    if not raw_subject:
        return "General System Requirement"
    s = raw_subject.strip()
    mapping = {
        "tech stack": "Architecture & Technology Stack",
        "technology stack": "Architecture & Technology Stack",
        "user role": "User Roles & Permissions",
        "user roles": "User Roles & Permissions",
        "auth": "Authentication & Access Control",
        "authentication": "Authentication & Access Control",
        "feature": "Core Functional Feature",
        "features": "Core Functional Feature",
        "constraint": "System Constraints & Rules",
        "constraints": "System Constraints & Rules",
        "integration": "External Integrations & APIs",
        "integrations": "External Integrations & APIs",
    }
    return mapping.get(s.lower(), s.title())

def _format_functional_requirement(idx: int, atom: RequirementAtom) -> str:
    domain = _clean_subject_domain(atom.subject)
    action = (atom.action or "").strip()
    constraint = (atom.constraint_text or "").strip()
    raw = (atom.raw_text or "").strip()

    if action:
        if action.lower().startswith(("the system", "the platform", "users", "allow", "provide", "support", "integrate", "require", "enable", "ensure")):
            req_text = action[0].upper() + action[1:]
        elif action.lower().startswith("use "):
            req_text = f"The system shall {action}."
        else:
            req_text = f"The system shall support {action}."
    elif raw:
        req_text = f"The system shall satisfy: {raw}"
    else:
        req_text = "The system shall satisfy the specified functional requirement."

    lines = [f"REQ-{idx:03d} [{domain}]", f"  • Specification: {req_text}"]
    if constraint and constraint.lower() not in ("n/a", "none", "unspecified", "empty"):
        lines.append(f"  • Constraint / Acceptance Rule: {constraint}")

    return "\n".join(lines)

@router.get("/project/{project_id}/latest")
async def get_latest_srs(
    project_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    await get_scoped_project(project_id, current_user, db)

    q = (
        select(SRSVersion)
        .where(SRSVersion.project_id == project_id)
        .order_by(SRSVersion.created_at.desc())
        .limit(1)
    )
    result = await db.execute(q)
    srs = result.scalar_one_or_none()

    if not srs:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No SRS document found for this project."
        )

    from app.models.contradiction import Contradiction
    from app.models.session import Session
    from app.models.change_request import ChangeRequest
    from sqlalchemy import or_

    session_ids_q = select(Session.id).where(Session.project_id == project_id)
    cr_ids_q = select(ChangeRequest.id).where(ChangeRequest.project_id == project_id)
    pending_c_res = await db.execute(
        select(Contradiction).where(
            or_(
                Contradiction.session_id.in_(session_ids_q),
                Contradiction.change_request_id.in_(cr_ids_q)
            ),
            Contradiction.status == "pending"
        )
    )
    pending_c_list = pending_c_res.scalars().all()
    pending_atom_ids = set()
    for pc in pending_c_list:
        if pc.atom_1_id:
            pending_atom_ids.add(pc.atom_1_id)
        if pc.atom_2_id:
            pending_atom_ids.add(pc.atom_2_id)

    atoms_res = await db.execute(
        select(RequirementAtom)
        .where(
            (RequirementAtom.session_id == srs.session_id) | (RequirementAtom.project_id == project_id)
        )
        .where(RequirementAtom.status == "active")
        .order_by(RequirementAtom.created_at.asc())
    )
    all_active_atoms = atoms_res.scalars().all()
    atoms = [a for a in all_active_atoms if a.id not in pending_atom_ids]

    sections = [
        {
            "title": "1. Executive Summary & Overview",
            "content": (
                f"Software Requirements Specification (v{srs.version}) generated by {srs.generated_by}. "
                f"This specification captures {len(atoms)} verified functional requirement(s) across "
                f"{len(set(_clean_subject_domain(a.subject) for a in atoms))} domain(s), "
                "sourced from client gathering sessions and validated for conflicts."
            ) if atoms else "No requirements captured yet."
        },
        {
            "title": "2. Functional Requirements",
            "content": "\n\n".join([
                _format_functional_requirement(idx, atom)
                for idx, atom in enumerate(atoms, start=1)
            ]) if atoms else "No active functional requirements extracted yet."
        },
        {
            "title": "3. Requirement Statements (Raw Captures)",
            "content": "\n".join([
                f"ORS-{idx:03d}: \"{atom.raw_text}\"" for idx, atom in enumerate(atoms, start=1)
            ]) if atoms else "No raw requirement statements captured."
        }
    ]

    download_url = StorageService.get_download_url(srs.file_url)

    return {
        "id": srs.id,
        "version": srs.version,
        "download_url": download_url,
        "sections": sections,
        "atoms": [
            {
                "id": str(a.id),
                "subject": a.subject,
                "action": a.action,
                "constraint_text": a.constraint_text,
                "raw_text": a.raw_text
            }
            for a in atoms
        ],
        "created_at": srs.created_at,
        "generated_by": srs.generated_by,
        "change_summary": srs.change_summary
    }

import os
from pathlib import Path
from fastapi.responses import FileResponse, RedirectResponse
from app.services.storage_service import get_s3_client, _BASE_DIR

@router.get("/download-file")
async def download_srs_file(
    key: str,
    token: Optional[str] = Query(None),
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db),
):
    if ".." in key:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid file key.",
        )
    s3 = get_s3_client()
    if s3 is None:
        file_path = _BASE_DIR / "storage_files" / key
        if not file_path.exists():

            srs_res = await db.execute(select(SRSVersion).where(SRSVersion.file_url == key))
            srs_rec = srs_res.scalar_one_or_none()
            if srs_rec:
                try:
                    import docx
                    file_path.parent.mkdir(parents=True, exist_ok=True)
                    doc = docx.Document()
                    doc.add_heading(f"SOFTWARE REQUIREMENTS SPECIFICATION (v{srs_rec.version})", level=1)
                    doc.add_paragraph(f"Generated by {srs_rec.generated_by}. {srs_rec.change_summary or ''}")
                    atoms_res = await db.execute(
                        select(RequirementAtom).where(
                            (RequirementAtom.project_id == srs_rec.project_id) | (RequirementAtom.session_id == srs_rec.session_id)
                        ).where(RequirementAtom.status == "active")
                    )
                    atoms = atoms_res.scalars().all()
                    if atoms:
                        doc.add_heading("Functional Requirements", level=2)
                        for idx, a in enumerate(atoms, start=1):
                            doc.add_paragraph(f"REQ-{idx:03d} [{a.subject or 'General'}]: {a.action or 'Unspecified'} - Constraint: {a.constraint_text or 'N/A'}")
                    doc.save(str(file_path))
                except Exception as e:
                    logger.warning(f"Could not auto-generate missing SRS docx on download: {e}")

        if not file_path.exists():
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="SRS document file not found. Try regenerating the SRS document.",
            )

        filename = os.path.basename(key)
        if not filename.endswith(".docx"):
            filename = f"{filename}.docx"

        return FileResponse(
            path=str(file_path),
            filename=filename,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "Access-Control-Expose-Headers": "Content-Disposition",
            }
        )
    else:
        url = StorageService.get_download_url(key)
        return RedirectResponse(url=url)

@router.get("/project/{project_id}/versions", response_model=List[SRSVersionRead])
async def list_srs_versions(
    project_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    limit: int = 50,
    offset: int = 0,
    db: AsyncSession = Depends(get_db)
):
    await get_scoped_project(project_id, current_user, db)

    q = (
        select(SRSVersion)
        .where(SRSVersion.project_id == project_id)
        .order_by(SRSVersion.created_at.desc())
        .limit(limit)
        .offset(offset)
    )
    result = await db.execute(q)
    versions = result.scalars().all()

    formatted_versions = []
    for v in versions:
        v_dict = {
            "id": v.id,
            "project_id": v.project_id,
            "session_id": v.session_id,
            "version": v.version,
            "file_url": StorageService.get_download_url(v.file_url),
            "generated_by": v.generated_by,
            "change_summary": v.change_summary,
            "llm_model": v.llm_model,
            "prompt_version": v.prompt_version,
            "generation_latency_ms": v.generation_latency_ms,
            "created_at": v.created_at,
        }
        formatted_versions.append(v_dict)
    return formatted_versions
@router.get("/version/{version_id}")
async def get_srs_version_details(
    version_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    srs = await db.get(SRSVersion, version_id)
    if not srs:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="SRS version not found."
        )

    from app.models.contradiction import Contradiction
    from app.models.session import Session
    from app.models.change_request import ChangeRequest
    from sqlalchemy import or_

    session_ids_q = select(Session.id).where(Session.project_id == srs.project_id)
    cr_ids_q = select(ChangeRequest.id).where(ChangeRequest.project_id == srs.project_id)
    pending_c_res = await db.execute(
        select(Contradiction).where(
            or_(
                Contradiction.session_id.in_(session_ids_q),
                Contradiction.change_request_id.in_(cr_ids_q)
            ),
            Contradiction.status == "pending"
        )
    )
    pending_c_list = pending_c_res.scalars().all()
    pending_atom_ids = set()
    for pc in pending_c_list:
        if pc.atom_1_id:
            pending_atom_ids.add(pc.atom_1_id)
        if pc.atom_2_id:
            pending_atom_ids.add(pc.atom_2_id)

    atoms_res = await db.execute(
        select(RequirementAtom)
        .where(
            (RequirementAtom.session_id == srs.session_id) | (RequirementAtom.project_id == srs.project_id)
        )
        .where(RequirementAtom.status == "active")
        .order_by(RequirementAtom.created_at.asc())
    )
    all_active_atoms = atoms_res.scalars().all()
    atoms = [a for a in all_active_atoms if a.id not in pending_atom_ids]

    sections = [
        {
            "title": "1. Executive Summary & Overview",
            "content": (
                f"Software Requirements Specification (v{srs.version}) generated by {srs.generated_by}. "
                f"This specification captures {len(atoms)} verified functional requirement(s) across "
                f"{len(set(_clean_subject_domain(a.subject) for a in atoms))} domain(s), "
                "sourced from client gathering sessions and validated for conflicts."
            ) if atoms else "No requirements captured yet."
        },
        {
            "title": "2. Functional Requirements",
            "content": "\n\n".join([
                _format_functional_requirement(idx, atom)
                for idx, atom in enumerate(atoms, start=1)
            ]) if atoms else "No active functional requirements extracted yet."
        },
        {
            "title": "3. Requirement Statements (Raw Captures)",
            "content": "\n".join([
                f"ORS-{idx:03d}: \"{atom.raw_text}\"" for idx, atom in enumerate(atoms, start=1)
            ]) if atoms else "No raw requirement statements captured."
        }
    ]

    download_url = StorageService.get_download_url(srs.file_url)

    return {
        "id": srs.id,
        "version": srs.version,
        "download_url": download_url,
        "sections": sections,
        "atoms": [
            {
                "id": str(a.id),
                "subject": a.subject,
                "action": a.action,
                "constraint_text": a.constraint_text,
                "raw_text": a.raw_text
            }
            for a in atoms
        ],
        "created_at": srs.created_at,
        "generated_by": srs.generated_by,
        "change_summary": srs.change_summary
    }

from app.services.srs_generator import SRSGenerator

@router.post("/project/{project_id}/generate")
async def generate_project_srs(
    project_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    await get_scoped_project(project_id, current_user, db)

    from app.models.session import Session
    sess_res = await db.execute(
        select(Session)
        .where(Session.project_id == project_id)
        .order_by(Session.started_at.desc())
        .limit(1)
    )
    latest_session = sess_res.scalar_one_or_none()

    if not latest_session:
        latest_session = Session(
            id=uuid.uuid4(),
            project_id=project_id,
            client_id=current_user.id if current_user.role == "client" else None,
            status="completed",
        )
        db.add(latest_session)
        await db.commit()
        await db.refresh(latest_session)

    srs = await SRSGenerator.generate_srs(latest_session.id, db)
    download_url = StorageService.get_download_url(srs.file_url)

    return {
        "id": srs.id,
        "version": srs.version,
        "download_url": download_url,
        "created_at": srs.created_at
    }

@router.get("/project/{project_id}/diff")
async def diff_srs_versions(
    project_id: uuid.UUID,
    v1_id: uuid.UUID,
    v2_id: uuid.UUID,
    current_user: User = Depends(require_roles("admin", "developer", "client")),
    db: AsyncSession = Depends(get_db)
):
    await get_scoped_project(project_id, current_user, db)

    srs_v1 = await db.get(SRSVersion, v1_id)
    srs_v2 = await db.get(SRSVersion, v2_id)

    if not srs_v1 or not srs_v2 or srs_v1.project_id != project_id or srs_v2.project_id != project_id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Specified SRS versions not found for this project."
        )

    atoms_v1_res = await db.execute(
        select(RequirementAtom)
        .where(
            RequirementAtom.project_id == project_id,
            RequirementAtom.created_at <= srs_v1.created_at
        )
    )
    atoms_v1 = {a.id: a for a in atoms_v1_res.scalars().all()}

    atoms_v2_res = await db.execute(
        select(RequirementAtom)
        .where(
            RequirementAtom.project_id == project_id,
            RequirementAtom.created_at <= srs_v2.created_at
        )
    )
    atoms_v2 = {a.id: a for a in atoms_v2_res.scalars().all()}

    added = [
        {"id": str(a.id), "raw_text": a.raw_text, "subject": a.subject, "action": a.action}
        for aid, a in atoms_v2.items() if aid not in atoms_v1
    ]
    removed = [
        {"id": str(a.id), "raw_text": a.raw_text, "subject": a.subject, "action": a.action}
        for aid, a in atoms_v1.items() if aid not in atoms_v2
    ]

    return {
        "v1": {"id": str(srs_v1.id), "version": srs_v1.version, "created_at": srs_v1.created_at},
        "v2": {"id": str(srs_v2.id), "version": srs_v2.version, "created_at": srs_v2.created_at},
        "added_requirements": added,
        "removed_requirements": removed,
        "net_change_count": len(added) - len(removed)
    }
