import React, { useState } from 'react';
import { Paper, Typography, Box, Button, Stack, Divider, Chip, CircularProgress } from '@mui/material';
import DownloadIcon from '@mui/icons-material/Download';
import HistoryIcon from '@mui/icons-material/History';
import { formatDateTime } from '../../utils/helpers';
import SRSSection from './SRSSection';
import { downloadSrsDocx } from '../../api/srs';
import { useToastStore } from '../../store/toastStore';

export const SRSViewer = ({ srsData, onShowHistory, projectName = 'Project' }) => {
  if (!srsData) return null;

  const { version, created_at, download_url, sections = [], atoms = [], generated_by, change_summary } = srsData;
  const showToast = useToastStore((s) => s.showToast);
  const [downloading, setDownloading] = useState(false);

  const handleDownload = async () => {
    if (!download_url) {
      showToast('Download link not available. Try regenerating the SRS document.', 'warning');
      return;
    }
    setDownloading(true);
    try {
      showToast('Preparing SRS document download…', 'info');
      const safeProjectName = (projectName || 'Project').replace(/[^a-zA-Z0-9_-]/g, '_');
      const filename = `${safeProjectName}_SRS_v${version || '1.0'}.docx`;
      await downloadSrsDocx(download_url, filename);
      showToast('SRS document downloaded successfully!', 'success');
    } catch (err) {
      console.error('[SRSViewer] Download failed:', err);
      const detail = err?.response?.data?.detail;
      if (detail) {
        showToast(detail, 'error');
      } else {
        showToast('Download failed. The SRS file may not exist — try regenerating it.', 'error');
      }
    } finally {
      setDownloading(false);
    }
  };

  const displaySections = sections.length > 0 ? sections : (
    atoms.length > 0
      ? [
          {
            title: '1. Executive Summary & Overview',
            content: `Software Requirements Specification (v${version || '1.0'}). Generated by ${generated_by || 'ARIA AI'}. ${change_summary || ''}`.trim(),
          },
          {
            title: '2. Functional Requirements',
            content: atoms.map((a, i) =>
              `[${i + 1}] ${a.subject || 'Unspecified'}: ${a.action || 'Unspecified'}` +
              (a.constraint_text ? ` (Constraint: ${a.constraint_text})` : '')
            ).join('\n\n'),
          },
          {
            title: '3. Requirement Statements (Raw Captures)',
            content: atoms.map((a) => `- "${a.raw_text}"`).join('\n'),
          },
        ]
      : [
          {
            title: '1. Executive Summary & Overview',
            content: 'No requirements have been captured yet for this project.',
          },
        ]
  );

  return (
    <Paper variant="outlined" sx={{ p: 4, borderRadius: 3, border: '1px solid', borderColor: 'divider' }}>
      {}
      <Box sx={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: 2, mb: 3 }}>
        <Box>
          <Stack direction="row" spacing={1.5} alignItems="center" sx={{ mb: 1 }}>
            <Typography variant="h4" sx={{ fontWeight: 700 }}>
              Software Requirements Specification
            </Typography>
            <Chip label={`v${version || '1.0'}`} color="primary" size="small" sx={{ fontWeight: 700 }} />
            {generated_by && <Chip label={`By: ${generated_by}`} variant="outlined" size="small" />}
          </Stack>
          <Typography variant="body2" color="text.secondary">
            Generated on {formatDateTime(created_at)}
            {atoms.length > 0 && (
              <Box component="span" sx={{ ml: 1.5, color: 'text.disabled' }}>
                · {atoms.length} requirement{atoms.length !== 1 ? 's' : ''}
              </Box>
            )}
          </Typography>
          {change_summary && (
            <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.5, fontStyle: 'italic' }}>
              {change_summary}
            </Typography>
          )}
        </Box>

        <Stack direction="row" spacing={1.5}>
          {onShowHistory && (
            <Button
              variant="outlined"
              color="primary"
              startIcon={<HistoryIcon />}
              onClick={onShowHistory}
            >
              History
            </Button>
          )}
          <Button
            variant="contained"
            color="secondary"
            startIcon={downloading ? <CircularProgress size={18} color="inherit" /> : <DownloadIcon />}
            disabled={downloading || !download_url}
            onClick={handleDownload}
          >
            {downloading ? 'Downloading…' : 'Download .DOCX'}
          </Button>
        </Stack>
      </Box>

      <Divider sx={{ mb: 4 }} />

      {}
      <Stack spacing={4}>
        {displaySections.map((sec, index) => (
          <SRSSection key={index} title={sec.title} content={sec.content} />
        ))}
      </Stack>
    </Paper>
  );
};

export default SRSViewer;
